name: Build and Test syntax
on: [push]
jobs:
  grammar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Extension
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Linting
        run: npm run lint
      - name: Test Syntax Highlighting
        run: npm run test:grammar
      - name: Test Unittests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
