on:
  release:
    types: [published]

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Package Release ${{ github.ref_name }}
        run: |
          echo "@@@@@@@@@: $GITHUB_REF_NAME"
          npm i -g vsce
          vsce package --no-git-tag-version ${GITHUB_REF_NAME:1}

      - name: Update package.json version
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "gnikit"
          author_email: giannis.nikiteas@gmail.com
          message: "ci: update package.json version"
          add: "package.json"

      - uses: softprops/action-gh-release@master
        with:
          files: ./*.vsix
